apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: Multi-Agent BIM System
spec:
  description: Deployment template for Multi-Agent BIM Backend and Frontend
  services:
    - name: backend
      spec:
        source:
          git:
            type: GITHUB
            # ⚠️ IMPORTANT: Replace this with your actual GitHub Repository ID
            # You can find the Repo ID by inspecting the network request when selecting a repo in Zeabur Dashboard,
            # or by listing repositories using the Zeabur CLI.
            repoID: REPLACE_WITH_YOUR_REPO_ID
            checkout:
              branch: main
        # Set the working directory to backend
        directory: backend
        ports:
          - port: 8000
            type: HTTP
        env:
          - key: OPENAI_API_KEY
            # It's recommended to not commit sensitive keys. You can set this to a placeholder or empty string
            # and configure it in the Zeabur Dashboard variables after deployment.
            value: sk-Dppz8ZLK62lWyZc7G3w3LtkJx7sNgmjdF65kzR7hKtQlnQDL
          - key: OPENAI_BASE_URL
            value: https://yunwu.ai/v1

    - name: frontend
      spec:
        source:
          git:
            type: GITHUB
            # ⚠️ IMPORTANT: Replace this with your actual GitHub Repository ID
            repoID: REPLACE_WITH_YOUR_REPO_ID
            checkout:
              branch: main
        # Set the working directory to frontend
        directory: frontend
        ports:
          - port: 80
            type: HTTP
        dependencies:
          - backend
